# Generated by Django 5.0.6 on 2024-06-03 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='name',
            field=models.CharField(default='name', max_length=50, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
